# Generated by Django 3.0.4 on 2021-10-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='this is the description'),
            preserve_default=False,
        ),
    ]
