# Generated by Django 3.0.4 on 2021-10-31 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211026_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='payment_option',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='charge_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paypal_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='WalletPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=50)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Payment')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=50)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='PaypalPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=50)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Payment')),
            ],
        ),
    ]
