# Generated by Django 3.0.4 on 2022-03-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211031_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripepayment',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='walletpayment',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='walletpayment',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='PaypalPayment',
        ),
        migrations.DeleteModel(
            name='StripePayment',
        ),
        migrations.DeleteModel(
            name='WalletPayment',
        ),
    ]
