# Generated by Django 4.0.3 on 2022-04-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_order_payment_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='amount',
            new_name='balance',
        ),
    ]
