# Generated by Django 4.0.3 on 2022-04-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_payment_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='charge_id',
            field=models.CharField(max_length=20),
        ),
    ]
