# Generated by Django 4.0.3 on 2022-04-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_payment_charge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='charge_id',
        ),
    ]
