# Generated by Django 4.0.3 on 2022-05-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_payment_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('CH', 'Children'), ('WA', 'Wathces'), ('AJ', 'Air Jordan'), ('SW', 'Sport wear'), ('OW', 'Out wear')], max_length=2),
        ),
    ]
