# Generated by Django 4.0.3 on 2022-05-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_item_thumbnail_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='display_image_one',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='display_image_three',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='display_image_two',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
