# Generated by Django 4.0.3 on 2022-06-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_item_display_image_one_item_display_image_three_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
