# Generated by Django 4.0.3 on 2022-06-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_order_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='charge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
